### ISSUE TITLE
Bot crashed on utf8 encoding

### ISSUE THREAD

**Issue by veiset** [veiset/Brunobot#21]
Will not terminate the connection, but the parser thread will stop working when this happens:

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/home/vz/dev/git/Brunobot/module/core/cparser.py", line 155, in run
    self.parser.parse(line)
  File "/home/vz/dev/git/Brunobot/module/core/cparser.py", line 57, in parse
    unicode(privmatch.group(5),'utf-8'))
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 13: invalid continuation byte

**Comment by andern** [comment]
Do you know how to reproduce this?

**Comment by veiset** [comment]
Nope, sorry.

**Comment by veiset** [comment]
Fixed by @andern. Cheers.
