### ISSUE TITLE
Bot sometimes not fully terminated with ctrl-c

### ISSUE THREAD

**Issue by andern** [veiset/Brunobot#27]
Reproducible: Happened more than once. Don't know how.

Log from terminal:

```
^C   
> .. Core Parser cparser.BufferReader().run(self) terminated.
> .. ThreadedManager threadmanager.ThreadedManager().run(self) terminated.
^C
^C


```

From ps:

```

$ ps -eLf|grep -i python
andern    3104  2205  3104  0    2 Apr21 pts/3    00:00:01 python2.7 main.py
andern    3104  2205  3115  0    2 Apr21 pts/3    00:00:00 python2.7 main.py
```

**Comment by andern** [comment]
```
$ kill -9 3104
```

Gives me:

```
^C
> .. Core Parser cparser.BufferReader().run(self) terminated.
> .. ThreadedManager threadmanager.ThreadedManager().run(self) terminated.
^C
^C


^C^CKilled
```

**Comment by veiset** [comment]
```
^C
> .. Core Parser cparser.BufferReader().run(self) terminated.
> .. ThreadedManager threadmanager.ThreadedManager().run(self) terminated.
> .. Connection connection.StayAwake().run(self) terminated.
```

So apparently it fails when trying to close toe Connection thread. I will look closer into this issue.

**Comment by veiset** [comment]
```
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    brunobot.modules.quit()
> .. Connection connection.StayAwake().run(self) terminated.
  File "/home/vz/dev/git/Brunobot/modulemanager.py", line 65, in quit
    self.mcore['connection'].quit()
  File "/home/vz/dev/git/Brunobot/module/core/connection.py", line 56, in quit
    self.irc.send(u'QUIT \n')
socket.error: [Errno 32] Broken pipe
```

**Comment by veiset** [comment]
```
> .. Connection connection.StayAwake().run(self) terminated.
> ++ Could not communicate with IRC socket
> .. Core Parser cparser.BufferReader().run(self) terminated.
> .. ThreadedManager threadmanager.ThreadedManager().run(self) terminated.
```

It looks like the 89ef93d commit fixed it. Closing it for now.
